//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 4.0.20824.0
//
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiManagerOutlookAddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过诸如 ResGen 或 Visual Studio 这样的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiManagerOutlookAddIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap espressoCup {
            get {
                object obj = ResourceManager.GetObject("espressoCup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap espressoCup_tall {
            get {
                object obj = ResourceManager.GetObject("espressoCup_tall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] SimpleFormRegionOfs {
            get {
                object obj = ResourceManager.GetObject("SimpleFormRegionOfs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt; 的本地化字符串
        ///&lt;FormRegion xmlns=&quot;http://schemas.microsoft.com/office/outlook/12/formregion.xsd&quot;&gt;
        ///  &lt;formRegionType&gt;separate&lt;/formRegionType&gt;
        ///  &lt;formRegionName&gt;UIM&lt;/formRegionName&gt;
        ///  &lt;showInspectorCompose&gt;true&lt;/showInspectorCompose&gt;
        ///  &lt;showInspectorRead&gt;true&lt;/showInspectorRead&gt;
        ///  &lt;showReadingPane&gt;false&lt;/showReadingPane&gt;
        ///  &lt;icons&gt;
        ///    &lt;page&gt;addin&lt;/page&gt;
        ///  &lt;/icons&gt;
        ///&lt;/FormRegion&gt;。
        /// </summary>
        internal static string SimpleFormRegionXml {
            get {
                return ResourceManager.GetString("SimpleFormRegionXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2006/01/customui&quot; 
        ///          onLoad=&quot;OnLoad&quot;&gt; 的本地化字符串
        ///  &lt;ribbon&gt;
        ///    &lt;tabs&gt;
        ///		&lt;tab idMso=&quot;TabAddIns&quot;&gt;
        ///			&lt;group id=&quot;uimGroup&quot; label=&quot;UI Manager&quot;&gt;
        ///				&lt;toggleButton id=&quot;toggleTaskPane&quot;
        ///							  label=&quot;TaskPane&quot;
        ///							  imageMso=&quot;ControlLayoutStacked&quot;
        ///							  size=&quot;large&quot;
        ///							  onAction=&quot;OnToggleTaskPane&quot; /&gt;
        ///			&lt;/group&gt;
        ///		&lt;/tab&gt;
        ///    &lt;/tabs&gt;
        ///  &lt;/ribbon&gt;
        ///&lt;/customUI&gt;
        ///.
        /// </summary>
        internal static string SimpleRibbon {
            get {
                return ResourceManager.GetString("SimpleRibbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2006/01/customui&quot; 
        ///          onLoad=&quot;OnLoad&quot;&gt; 的本地化字符串
        ///  &lt;ribbon&gt;
        ///    &lt;tabs&gt;
        ///		&lt;tab idMso=&quot;TabAddIns&quot;&gt;
        ///			&lt;group id=&quot;uimGroup&quot; label=&quot;UI Manager&quot;&gt;
        ///				&lt;toggleButton id=&quot;toggleTaskPane&quot;
        ///							  label=&quot;TaskPane&quot;
        ///							  imageMso=&quot;ControlLayoutStacked&quot;
        ///							  size=&quot;large&quot;
        ///							  onAction=&quot;OnToggleTaskPane&quot; /&gt;
        ///			&lt;/group&gt;
        ///			&lt;group id=&quot;mailServiceGroup&quot;
        ///				   label=&quot;Add-in Services&quot;
        ///				   getVisible=&quot;GetVisible&quot;&gt;
        ///				&lt;button id=&quot;sendList&quot;
        ///					 [字符串剩余部分已截断]&quot;;。
        /// </summary>
        internal static string TaskRibbon {
            get {
                return ResourceManager.GetString("TaskRibbon", resourceCulture);
            }
        }
    }
}
