#pragma once


#define WIZ_HTML_COLLECTOR_DOWNLOAD_FILE			0x01
#define WIZ_HTML_COLLECTOR_SAVE_IMAGE				0x02
#define WIZ_HTML_COLLECTOR_SAVE_SCRIPT				0x04
#define WIZ_HTML_COLLECTOR_SAVE_FLASH				0x08
#define WIZ_HTML_COLLECTOR_SAVE_ALL_FRAME			0x10
#define WIZ_HTML_COLLECTOR_MODIFY_LINK				0x20


