//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 4.0.20826.0
//
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAnalysisExcel.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过诸如 ResGen 或 Visual Studio 这样的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataAnalysisExcel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似“添加新日期”的本地化字符串。
        /// </summary>
        internal static string AddNewDateButton {
            get {
                return ResourceManager.GetString("AddNewDateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“平均销售单位”的本地化字符串。
        /// </summary>
        internal static string AverageOfUnitsSold {
            get {
                return ResourceManager.GetString("AverageOfUnitsSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“平均利润”的本地化字符串。
        /// </summary>
        internal static string AverageProfit {
            get {
                return ResourceManager.GetString("AverageProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“平均销售”的本地化字符串。
        /// </summary>
        internal static string AverageSold {
            get {
                return ResourceManager.GetString("AverageSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“平均”的本地化字符串。
        /// </summary>
        internal static string AveragesPivotTableName {
            get {
                return ResourceManager.GetString("AveragesPivotTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“创建非计划订单”的本地化字符串。
        /// </summary>
        internal static string CreateUnscheduledOrderRecommendation {
            get {
                return ResourceManager.GetString("CreateUnscheduledOrderRecommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“当前库存”的本地化字符串。
        /// </summary>
        internal static string CurrentInventoryHeader {
            get {
                return ResourceManager.GetString("CurrentInventoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“您必须输入 {0:d} 的全部冰激凌风味的日末库存值，才可以创建订单或添加新的销售数据。”的本地化字符串。
        /// </summary>
        internal static string DataIncompleteError {
            get {
                return ResourceManager.GetString("DataIncompleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“日期”的本地化字符串。
        /// </summary>
        internal static string DateHeader {
            get {
                return ResourceManager.GetString("DateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“交货日期”的本地化字符串。
        /// </summary>
        internal static string DeliveryDateHeader {
            get {
                return ResourceManager.GetString("DeliveryDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“实际日末库存”的本地化字符串。
        /// </summary>
        internal static string EodInventoryHeader {
            get {
                return ResourceManager.GetString("EodInventoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“估计库存”的本地化字符串。
        /// </summary>
        internal static string EstimatedInventoryHeader {
            get {
                return ResourceManager.GetString("EstimatedInventoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“冰淇淋”的本地化字符串。
        /// </summary>
        internal static string IceCreamHeader {
            get {
                return ResourceManager.GetString("IceCreamHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“库存”的本地化字符串。
        /// </summary>
        internal static string InventoryHeader {
            get {
                return ResourceManager.GetString("InventoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“每日最多销售”的本地化字符串。
        /// </summary>
        internal static string MaxDailySalesHeader {
            get {
                return ResourceManager.GetString("MaxDailySalesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“净收益”的本地化字符串。
        /// </summary>
        internal static string NetGainHeader {
            get {
                return ResourceManager.GetString("NetGainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“订货日期”的本地化字符串。
        /// </summary>
        internal static string OrderDateHeader {
            get {
                return ResourceManager.GetString("OrderDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“订货数量”的本地化字符串。
        /// </summary>
        internal static string OrderQuantityHeader {
            get {
                return ResourceManager.GetString("OrderQuantityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“订单(&amp;R)”的本地化字符串。
        /// </summary>
        internal static string OrdersMenu {
            get {
                return ResourceManager.GetString("OrdersMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“订单”的本地化字符串。
        /// </summary>
        internal static string OrdersToolbar {
            get {
                return ResourceManager.GetString("OrdersToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“利润”的本地化字符串。
        /// </summary>
        internal static string ProfitHeader {
            get {
                return ResourceManager.GetString("ProfitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“计划库存”的本地化字符串。
        /// </summary>
        internal static string ProjectedInventoryHeader {
            get {
                return ResourceManager.GetString("ProjectedInventoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“计划销售”的本地化字符串。
        /// </summary>
        internal static string ProjectedSalesHeader {
            get {
                return ResourceManager.GetString("ProjectedSalesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“建议”的本地化字符串。
        /// </summary>
        internal static string RecommendationHeader {
            get {
                return ResourceManager.GetString("RecommendationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“销售和利润”的本地化字符串。
        /// </summary>
        internal static string SalesAndProfitPivotTableName {
            get {
                return ResourceManager.GetString("SalesAndProfitPivotTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“保存数据”的本地化字符串。
        /// </summary>
        internal static string SaveDataButton {
            get {
                return ResourceManager.GetString("SaveDataButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“日期:”的本地化字符串。
        /// </summary>
        internal static string Sheet1DateLabel {
            get {
                return ResourceManager.GetString("Sheet1DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“库存”的本地化字符串。
        /// </summary>
        internal static string Sheet1Name {
            get {
                return ResourceManager.GetString("Sheet1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“库存控制”的本地化字符串。
        /// </summary>
        internal static string Sheet1Title {
            get {
                return ResourceManager.GetString("Sheet1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“冰淇淋”的本地化字符串。
        /// </summary>
        internal static string Sheet2IceCreamLabel {
            get {
                return ResourceManager.GetString("Sheet2IceCreamLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“详细信息”的本地化字符串。
        /// </summary>
        internal static string Sheet2Name {
            get {
                return ResourceManager.GetString("Sheet2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“库存详细信息”的本地化字符串。
        /// </summary>
        internal static string Sheet2Title {
            get {
                return ResourceManager.GetString("Sheet2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“销售”的本地化字符串。
        /// </summary>
        internal static string SoldHeader {
            get {
                return ResourceManager.GetString("SoldHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“销售单位标准偏差”的本地化字符串。
        /// </summary>
        internal static string StdDevOfUnitsSold {
            get {
                return ResourceManager.GetString("StdDevOfUnitsSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“销售单位”的本地化字符串。
        /// </summary>
        internal static string UnitsSoldHeader {
            get {
                return ResourceManager.GetString("UnitsSoldHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“创建非计划订单(&amp;U)”的本地化字符串。
        /// </summary>
        internal static string UnscheduledMenu {
            get {
                return ResourceManager.GetString("UnscheduledMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“低库存项的非计划订单的估计成本为 {0:.00}。非计划订单不是建议值。”的本地化字符串。
        /// </summary>
        internal static string UnscheduledOrderNotRecommended {
            get {
                return ResourceManager.GetString("UnscheduledOrderNotRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“低库存项的非计划订单的估计利润为 {0:.00}。”的本地化字符串。
        /// </summary>
        internal static string UnscheduledOrderRecommended {
            get {
                return ResourceManager.GetString("UnscheduledOrderRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“无法创建非计划订单工作表。请验证是否可将新的工作表添加到工作簿并且不存在名为 {0} 的工作表。”的本地化字符串。
        /// </summary>
        internal static string UnscheduledOrderSheetCreationError {
            get {
                return ResourceManager.GetString("UnscheduledOrderSheetCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“非计划订单: {0}”的本地化字符串。
        /// </summary>
        internal static string UnscheduledOrderSheetName {
            get {
                return ResourceManager.GetString("UnscheduledOrderSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“创建每周订单(&amp;W)”的本地化字符串。
        /// </summary>
        internal static string WeeklyMenu {
            get {
                return ResourceManager.GetString("WeeklyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“无法创建‘每周订单’工作表。请验证是否可将新的工作表添加到工作簿并且不存在名为 {0} 的工作表。”的本地化字符串。
        /// </summary>
        internal static string WeeklyOrderSheetCreationError {
            get {
                return ResourceManager.GetString("WeeklyOrderSheetCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“每周订单: {0}”的本地化字符串。
        /// </summary>
        internal static string WeeklyOrderSheetName {
            get {
                return ResourceManager.GetString("WeeklyOrderSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似“已存在名为 {0} 的工作表。”的本地化字符串。
        /// </summary>
        internal static string WorksheetExistsError {
            get {
                return ResourceManager.GetString("WorksheetExistsError", resourceCulture);
            }
        }
    }
}
