#pragma once

#include "WizHtmlCollectorDef.h"


#define WIZHTMLSAVER_FLAGS_NO_SCRIPT		(WIZ_HTML_COLLECTOR_DOWNLOAD_FILE | WIZ_HTML_COLLECTOR_SAVE_IMAGE | WIZ_HTML_COLLECTOR_SAVE_FLASH | WIZ_HTML_COLLECTOR_SAVE_ALL_FRAME | WIZ_HTML_COLLECTOR_MODIFY_LINK)
#define WIZHTMLSAVER_FLAGS_INCLUDE_SCRIPT   (WIZ_HTML_COLLECTOR_SAVE_SCRIPT | WIZHTMLSAVER_FLAGS_NO_SCRIPT)

#define WIZHTMLSAVER_FLAGS_SAVE_SEL						0x00010000
#define WIZHTMLSAVER_FLAGS_SAVE_CONTENT_ONLY			0x00020000
#define WIZHTMLSAVER_FLAGS_SAVE_TEXT_ONLY				0x00040000
#define WIZHTMLSAVER_FLAGS_SHOW_PROGRESS				0x00080000
#define WIZHTMLSAVER_FLAGS_ALLOW_AUTO_GET_CONTENT		0x00100000
#define WIZHTMLSAVER_FLAGS_INCLUDE_CSS_ALWAYS			0x00200000



inline UINT WizHtmlSaverGetCollectorFlags(BOOL bSaveScript)
{
	return bSaveScript ? WIZHTMLSAVER_FLAGS_INCLUDE_SCRIPT : WIZHTMLSAVER_FLAGS_NO_SCRIPT;
}
